---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[chef-zeromq::default]
    attributes:
  - name: with_ruby
    run_list:
      - recipe[chef-zeromq::default]
      - recipe[chef-ruby::default]
    attributes: {ruby: {version: "1.9.2-p320"}}